"""empty message

Revision ID: 094b1008b053
Revises: 4b6b6053b88c
Create Date: 2021-06-14 17:35:40.310587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '094b1008b053'
down_revision = '4b6b6053b88c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
