"""empty message

Revision ID: 25240101bad7
Revises: 62d9c2bae940
Create Date: 2021-06-14 19:31:21.771407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25240101bad7'
down_revision = '62d9c2bae940'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('goal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('goal')
    # ### end Alembic commands ###
