"""empty message

Revision ID: 268852c36865
Revises: afc38e1b3a66
Create Date: 2021-06-14 11:01:23.686032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268852c36865'
down_revision = 'afc38e1b3a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_column('goal', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('goal', sa.Column('goal_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('goal', 'id')
    # ### end Alembic commands ###
