"""empty message

Revision ID: 499d706ad3de
Revises: b7ce402929ac
Create Date: 2021-06-14 17:24:55.882982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499d706ad3de'
down_revision = 'b7ce402929ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
