"""empty message

Revision ID: 4d5d03b10019
Revises: 5d3ef5e8db55
Create Date: 2021-06-15 12:50:20.967617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d5d03b10019'
down_revision = '5d3ef5e8db55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'task', 'goal', ['goal_id'], ['goal_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    # ### end Alembic commands ###
