"""empty message

Revision ID: 651aef3a2fe0
Revises: 1c916897349b
Create Date: 2021-06-14 17:12:03.178082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '651aef3a2fe0'
down_revision = '1c916897349b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
