"""empty message

Revision ID: 69994d3cf45f
Revises: 280199db43d2
Create Date: 2021-06-14 12:59:52.993725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69994d3cf45f'
down_revision = '280199db43d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
