"""empty message

Revision ID: 86487318a410
Revises: 
Create Date: 2021-06-09 12:18:41.790660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86487318a410'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('goal_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('goal_id')
    )
    op.drop_column('task', 'is_complete')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_complete', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_table('goal')
    # ### end Alembic commands ###
