"""empty message

Revision ID: aea75a1fbbe9
Revises: d95606c21adc
Create Date: 2021-06-07 15:48:13.536459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aea75a1fbbe9'
down_revision = 'd95606c21adc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('title', sa.VARCHAR(length=25), nullable=True))
    op.drop_column('task', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('name', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.drop_column('task', 'title')
    # ### end Alembic commands ###
